### ISSUE TITLE
How to create dir to place the images

### ISSUE THREAD

**Issue by lsqswl** [bspaulding/rollup-plugin-image-files#4]
The images are placed in root dir now.

**Comment by njleonzhang** [comment]
there is a bug here, so dest can not work

https://github.com/bspaulding/rollup-plugin-image-files/blob/0a6b5a6d7fb930c8735504fae9dcee7ee0cf4769/src/index.js#L7-L21

`options` of `image()` is override by `options` of `generateBundle()`

**Comment by njleonzhang** [comment]
I have create a pr https://github.com/bspaulding/rollup-plugin-image-files/pull/7

**Comment by bspaulding** [comment]
I believe `dest` was part of an older version of the rollup plugin system. What version of rollup are ya'll using? On newest rollup, you should be setting the output directory/file in `output.file` or `output.dir`.

**Comment by bspaulding** [comment]
Closed due to inactivity. Please re-open with more info if this is still an issue for you!
